### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by albertyw** [hhonasoge/myblog#4]
Your current list of dependencies is pretty out of date.

```
appdirs==1.4.3
certifi==2019.9.11
chardet==3.0.4
configparser==4.0.2
contextlib2==0.6.0.post1
distlib==0.3.0
Django==1.11.28
filelock==3.0.12
idna==2.8
importlib-metadata==1.5.0
importlib-resources==1.1.0
pathlib2==2.3.5
pytz==2019.3
qualname==0.1.0
requests==2.22.0
scandir==1.10.0
singledispatch==3.4.0.3
six==1.14.0
typing==3.7.4.1
urllib3==1.25.6
varsnap==0.8.3
virtualenv==20.0.7
zipp==1.2.0
```

I recmomend upgrading Django to the current release (3.0.4) and removing any dependencies you're not actively using (which is most of these) so that their versions can float and be set by other dependencies.

**Comment by albertyw** [comment]
Outdated dependencies after a fresh pip install:

```
(myblog) albertyw@personal ~/myblog $ pip list --outdated
Package             Version   Latest     Type
------------------- --------- ---------- -----
certifi             2019.9.11 2019.11.28 wheel
Django              1.11.28   3.0.4      wheel
idna                2.8       2.9        wheel
importlib-resources 1.1.0     1.3.1      wheel
requests            2.22.0    2.23.0     wheel
urllib3             1.25.6    1.25.8     wheel
varsnap             0.8.3     1.1.1      wheel
virtualenv          20.0.7    20.0.10    wheel
zipp                1.2.0     3.1.0      wheel
```

**Comment by hhonasoge** [comment]
@albertyw have you used https://github.com/bndr/pipreqs before? would you recommend it as a way to determine which libraries are actively being used in a Python project? To generate this requirements.txt file, I just did `pip freeze > requirements.txt` but I think that basically just wrote out all the package I pip installed on my machine

**Comment by albertyw** [comment]
I haven't used that library before.  There's a whole of of different libraries out there to help manage dependencies and your environment.  The tried and tested method I would recommend is using `grep import` to find out what direct dependencies you need, use `pip` to install them, and use `virtualenv` to make sure they're installed in the right place.
