### ISSUE TITLE
Auth credentials in database

### ISSUE THREAD

**Issue by albertyw** [hhonasoge/myblog#9]
I see you committed your database in `db.sqlite3`.  If you're not planning on making writes in production, this isn't too bad but it does contain all the data for all your tables including the hashed passwords for your two user accounts.  Finding the real passwords is hard but not impossible so I recommend rotating passwords if you've used the same ones anywhere else.

**Comment by hhonasoge** [comment]
Thanks @albertyw , I've rotated my passwords in other accounts.
